AWSTemplateFormatVersion: "2010-09-09"
Description: AgentCore Runtime for MCP server

Parameters:
  pRuntimeName:
    Type: String
    Description: Name of the AgentCore Runtime
  pAccountId:
    Type: String
    Description: AWS account ID
  pRegion:
    Type: String
    Description: AWS region
  pS3Bucket:
    Type: String
    Description: S3 bucket containing the deployment package
  pS3Prefix:
    Type: String
    Description: S3 key for the deployment package zip
  pCognitoIssuer:
    Type: String
    Description: Cognito Issuer URL for JWT validation (NONE = no JWT auth)
    Default: "NONE"
  pCognitoAudience:
    Type: String
    Description: Cognito Client ID used as JWT audience (NONE = no JWT auth)
    Default: "NONE"

Conditions:
  HasJWTAuth: !Not [!Equals [!Ref pCognitoIssuer, "NONE"]]

Resources:
  RuntimeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${pRuntimeName}-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: bedrock-agentcore.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref pAccountId
              ArnLike:
                aws:SourceArn: !Sub "arn:aws:bedrock-agentcore:${pRegion}:${pAccountId}:*"
      Policies:
        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:DescribeLogGroups
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:DescribeLogStreams
                  - logs:FilterLogEvents
                  - logs:GetLogEvents
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${pRegion}:${pAccountId}:log-group:/aws/bedrock-agentcore/runtimes/*"
              - Effect: Allow
                Action:
                  - xray:PutTraceSegments
                  - xray:PutTelemetryRecords
                Resource: "*"

  Runtime:
    Type: AWS::BedrockAgentCore::Runtime
    DependsOn: RuntimeRole
    Properties:
      AgentRuntimeName: !Ref pRuntimeName
      Description: MCP server for interceptors demo
      RoleArn: !GetAtt RuntimeRole.Arn
      AgentRuntimeArtifact:
        CodeConfiguration:
          Code:
            S3:
              Bucket: !Ref pS3Bucket
              Prefix: !Ref pS3Prefix
          Runtime: PYTHON_3_12
          EntryPoint:
            - start.py
      NetworkConfiguration:
        NetworkMode: PUBLIC
      ProtocolConfiguration: MCP
      EnvironmentVariables:
        AGENT_OBSERVABILITY_ENABLED: "true"
        AWS_REGION: !Ref pRegion
      RequestHeaderConfiguration:
        RequestHeaderAllowlist:
          - X-Amzn-Bedrock-AgentCore-Runtime-Custom-Interceptor-Demo
      AuthorizerConfiguration: !If
        - HasJWTAuth
        - CustomJWTAuthorizer:
            DiscoveryUrl: !Sub "${pCognitoIssuer}/.well-known/openid-configuration"
            AllowedClients:
              - !Ref pCognitoAudience
        - !Ref AWS::NoValue

Outputs:
  oRuntimeArn:
    Description: AgentCore Runtime ARN
    Value: !GetAtt Runtime.AgentRuntimeArn
  oRuntimeId:
    Description: AgentCore Runtime ID
    Value: !GetAtt Runtime.AgentRuntimeId
  oRuntimeRoleArn:
    Description: Runtime execution role ARN
    Value: !GetAtt RuntimeRole.Arn
